spring.application.name=icecream
server.port=8083

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/icecream?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

spring.datasource.username=
spring.datasource.password=

mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
logging.level.com.parfait.icecream.dao=debug